spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: shipment-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:8001
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: ${CONFIG_SERVER_URL:http://localhost:6969}
      request-connect-timeout: 5000
      request-read-timeout: 5000
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 1000
        max-interval: 2000
        multiplier: 1.1
      username: admin
      password: 123456

server:
  port: 8004

queue:
  shipment:
    queue: shipment-queue
    exchange: shipment-exchange
    routingKey: shipment-routing-key
