spring:
  application:
    name: shipment-service
  datasource:
    url: jdbc:mysql://localhost:3306/shipment-service
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update